# fly.toml app configuration file generated for wheels on 2023-07-19T10:46:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wheels"
primary_region = "cdg"

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
